Algoritmo "Variáveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Variáveis
// Autor(a)    : Max Yuri Ferreira dos Santos
// Data atual  : 17/04/2020
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

    primeiroNome, segundoNome, cidade, endereco: caractere
    idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Fimalgoritmo